import { App, Notice, TFile, TFolder, normalizePath } from 'obsidian'
import type { Project, Task, StatusConfig } from '../types'
import { makeProject, makeTask } from '../types'
import {
  updateTaskInTree,
  deleteTaskFromTree,
  addTaskToTree,
  flattenTasks,
  moveTaskInTree,
  cloneTaskSubtree
} from './TaskTreeOps'
import {
  findParentId,
  findTaskById,
  indexAddSubtree,
  indexRemoveSubtree,
  indexSetParent,
  rebuildTaskIndex
} from './TaskIndex'
import { computeSchedule } from './Scheduler'
import { archiveTask as doArchiveTask, unarchiveTask as doUnarchiveTask } from './ArchiveOps'
import { parseFrontmatter, stripAutoGeneratedContent, FRONTMATTER_KEY, TASK_FRONTMATTER_KEY } from './YamlParser'
import { hydrateProjectFromFrontmatter, hydrateTaskFromFile, hydrateTasks } from './YamlHydrator'
import { serializeProject, serializeTask, taskFilePath } from './YamlSerializer'
import { ensureFolder } from './vaultFs'

/**
 * Pick a save path for a task. New tasks get the bare-slug name from
 * `taskFilePath`. Legacy `<slug>-<id8>.md` files are kept in place as long
 * as their slug still matches the current title, so untouched vaults don't
 * churn just because the suffix scheme changed.
 */
function resolveTaskPath(task: Task, folder: string, previousPath: string | undefined): string {
  const desired = taskFilePath(task.title, folder)
  if (!previousPath) return desired
  const desiredBasename = desired.slice(desired.lastIndexOf('/') + 1).replace(/\.md$/, '')
  const previousFolder = previousPath.slice(0, previousPath.lastIndexOf('/'))
  const previousBasename = previousPath.slice(previousPath.lastIndexOf('/') + 1).replace(/\.md$/, '')
  const legacyBasename = `${desiredBasename}-${task.id.slice(0, 8)}`
  if (previousFolder === folder && previousBasename === legacyBasename) return previousPath
  return desired
}

/** Thrown when saving a task would collide with an existing file in the vault. */
export class TaskFileNameConflictError extends Error {
  constructor(public readonly path: string) {
    super(`A note named "${fileNameFromPath(path)}" already exists.`)
    this.name = 'TaskFileNameConflictError'
  }

  get fileName(): string {
    return fileNameFromPath(this.path)
  }
}

function fileNameFromPath(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1).replace(/\.md$/, '')
}

/**
 * Handles all read/write operations against the Obsidian vault.
 *
 * Storage layout:
 *   Projects/<ProjectName>.md         — project metadata (no task data)
 *   Projects/<ProjectName>/<slug>.md  — one .md per task
 *
 * The in-memory Project.tasks tree is assembled on load from individual
 * task files and remains unchanged for views.
 */
export class ProjectStore {
  /** Per-project promise chains to serialize concurrent saves */
  private saveQueues = new Map<string, Promise<void>>()

  /** Task IDs whose .md file needs rewriting on the next save. Tasks with no filePath are always written. */
  private dirtyTasks = new Map<string, Set<string>>()

  /**
   * Paths we've just written or trashed ourselves, timestamped. The view's
   * modify/delete listeners check this to skip reloads on self-writes.
   * Only mark before vault.modify or fileManager.trashFile. vault.create fires
   * a different event we don't listen for, so marking creates would leak.
   * Stale entries (older than the window) are treated as never-consumed.
   */
  private selfWrites = new Map<string, number>()
  private static readonly SELF_WRITE_WINDOW_MS = 5000

  constructor(
    private app: App,
    private getStatuses: () => StatusConfig[] = () => []
  ) {}

  // ─── Dirty tracking ───────────────────────────────────────────────────────

  private markDirty(project: Project, taskIds: Iterable<string>): void {
    let set = this.dirtyTasks.get(project.filePath)
    if (!set) {
      set = new Set()
      this.dirtyTasks.set(project.filePath, set)
    }
    for (const id of taskIds) set.add(id)
  }

  private markSubtreeDirty(project: Project, taskId: string): void {
    const task = findTaskById(project, taskId)
    if (!task) return
    this.markDirty(project, [taskId])
    for (const ft of flattenTasks(task.subtasks)) {
      this.markDirty(project, [ft.task.id])
    }
  }

  private markAllDirty(project: Project): void {
    const ids: string[] = []
    for (const ft of flattenTasks(project.tasks)) ids.push(ft.task.id)
    this.markDirty(project, ids)
  }

  private clearDirty(project: Project): void {
    this.dirtyTasks.delete(project.filePath)
  }

  // ─── Self-write tracking ──────────────────────────────────────────────────

  private markSelfWrite(path: string): void {
    this.selfWrites.set(path, Date.now())
  }

  /** Returns true if we wrote this path recently. Consumes the marker either way. */
  consumeSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    if (ts === undefined) return false
    this.selfWrites.delete(path)
    return Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  // ─── Folder helpers ────────────────────────────────────────────────────────

  async ensureFolder(folderPath: string): Promise<void> {
    await ensureFolder(this.app, folderPath)
  }

  /** Get the task subfolder path for a project */
  private projectTaskFolder(project: Project): string {
    return project.filePath.replace(/\.md$/, '_tasks')
  }

  // ─── Load ──────────────────────────────────────────────────────────────────

  async loadAllProjects(folder: string): Promise<Project[]> {
    await this.ensureFolder(folder)
    // Walk the projects folder directly. Don't scan the whole vault.
    const folderObj = this.app.vault.getAbstractFileByPath(folder)
    const files: TFile[] = []
    if (folderObj instanceof TFolder) {
      for (const child of folderObj.children) {
        if (child instanceof TFile && child.extension === 'md') files.push(child)
      }
    }
    const loaded = await Promise.all(files.map((f) => this.loadProject(f)))
    const projects = loaded.filter((p): p is Project => p !== null)
    return projects.sort((a, b) => a.title.localeCompare(b.title))
  }

  async loadProject(file: TFile): Promise<Project | null> {
    try {
      // Fast path: pull frontmatter from Obsidian's metadataCache, skip the disk read.
      // Old-format projects (embedded tasks) need the cache to expose `tasks`; if it
      // doesn't, fall back to reading and parsing the file ourselves.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      let frontmatter: Record<string, unknown> | null = null
      let body: string | null = null
      if (cached && cached[FRONTMATTER_KEY] === true) {
        frontmatter = cached
      } else {
        const content = await this.app.vault.cachedRead(file)
        const parsed = parseFrontmatter(content)
        frontmatter = parsed.frontmatter
        body = parsed.body
      }
      if (!frontmatter || frontmatter[FRONTMATTER_KEY] !== true) return null

      const hasEmbeddedTasks = Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0

      const project = hydrateProjectFromFrontmatter(frontmatter, body, file.path, file.basename)

      if (hasEmbeddedTasks) {
        project.tasks = hydrateTasks((frontmatter.tasks as unknown[]) ?? [])
        rebuildTaskIndex(project)
        // Old format: no per-task files on disk yet, so mark everything dirty.
        this.markAllDirty(project)
      } else {
        const taskFolder = this.projectTaskFolder(project)
        const taskIds = Array.isArray(frontmatter.taskIds) ? (frontmatter.taskIds as string[]) : []
        project.tasks = await this.loadTasksFromFolder(taskFolder, taskIds)
        rebuildTaskIndex(project)
        // Memory matches disk now, drop any stale dirty entries.
        this.clearDirty(project)
      }

      return project
    } catch (e) {
      console.error(`[PM] Failed to load project ${file.path}:`, e)
      new Notice(`Project Manager: Failed to load "${file.basename}". Check console for details.`)
      return null
    }
  }

  private async loadTasksFromFolder(folderPath: string, topLevelIds: string[]): Promise<Task[]> {
    const folder = this.app.vault.getAbstractFileByPath(folderPath)
    if (!(folder instanceof TFolder)) return []

    const taskMap = new Map<string, Task>()
    const subtaskIdsMap = new Map<string, string[]>()
    const parentIdMap = new Map<string, string>()
    const archivePrefix = normalizePath(folderPath + '/Archive') + '/'

    // Walk the task folder directly (plus Archive). Don't scan the whole vault.
    const files: TFile[] = []
    const collect = (f: TFolder): void => {
      for (const child of f.children) {
        if (child instanceof TFile && child.extension === 'md') files.push(child)
        else if (child instanceof TFolder) collect(child)
      }
    }
    collect(folder)

    const results = await Promise.all(files.map((file) => this.loadTaskFile(file)))
    for (let i = 0; i < files.length; i++) {
      const { task, subtaskIds, parentId } = results[i]
      if (task) {
        if (files[i].path.startsWith(archivePrefix)) {
          task.archived = true
        }
        taskMap.set(task.id, task)
        if (subtaskIds.length) subtaskIdsMap.set(task.id, subtaskIds)
        if (parentId) parentIdMap.set(task.id, parentId)
      }
    }

    for (const [taskId, sids] of subtaskIdsMap) {
      const task = taskMap.get(taskId)
      if (!task) continue
      task.subtasks = []
      for (const sid of sids) {
        const sub = taskMap.get(sid)
        if (sub) task.subtasks.push(sub)
      }
    }

    // Self-healing: re-parent orphaned tasks using parentId from their files
    const childIds = new Set<string>()
    for (const t of taskMap.values()) {
      for (const s of t.subtasks) childIds.add(s.id)
    }
    for (const [taskId, pid] of parentIdMap) {
      if (childIds.has(taskId)) continue // already parented
      const parent = taskMap.get(pid)
      if (!parent) continue
      const task = taskMap.get(taskId)
      if (!task) continue
      parent.subtasks.push(task)
      childIds.add(taskId)
      // Ensure parent's subtaskIds stay in sync
      if (!subtaskIdsMap.has(pid)) subtaskIdsMap.set(pid, [])
      const sids = subtaskIdsMap.get(pid)
      if (sids && !sids.includes(taskId)) sids.push(taskId)
      console.warn(
        `[PM] Self-healed orphan: re-parented task "${task.title}" (${taskId}) under "${parent.title}" (${pid})`
      )
    }

    const result: Task[] = []
    const pushed = new Set<string>()
    for (const id of topLevelIds) {
      if (pushed.has(id)) continue
      const task = taskMap.get(id)
      if (task) {
        result.push(task)
        pushed.add(id)
      }
    }
    for (const task of taskMap.values()) {
      if (pushed.has(task.id)) continue
      if (!childIds.has(task.id)) result.push(task)
    }

    return result
  }

  async loadTaskFile(file: TFile): Promise<{ task: Task | null; subtaskIds: string[]; parentId: string | null }> {
    try {
      // Fast path: pull frontmatter from Obsidian's metadataCache and skip the body
      // read. The description stays empty and `descriptionLoaded` is false until
      // ensureTaskBody fills it (on modal open or before a save).
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      if (cached && cached[TASK_FRONTMATTER_KEY] === true) {
        return hydrateTaskFromFile(cached, null, file.path)
      }

      const content = await this.app.vault.cachedRead(file)
      const { frontmatter, body } = parseFrontmatter(content)
      if (!frontmatter || frontmatter[TASK_FRONTMATTER_KEY] !== true) {
        return { task: null, subtaskIds: [], parentId: null }
      }

      return hydrateTaskFromFile(frontmatter, body, file.path)
    } catch (e) {
      if (e instanceof Error && e.message.includes('ENOENT')) {
        console.warn(`[PM] Task file no longer exists, skipping: ${file.path}`)
      } else {
        console.error(`[PM] Failed to load task ${file.path}:`, e)
        new Notice(`Project Manager: Failed to load task "${file.basename}". Check console for details.`)
      }
      return { task: null, subtaskIds: [], parentId: null }
    }
  }

  /**
   * Read the task's file body and populate its description if not already loaded.
   * Callers: modal open (so the user sees the real description) and saveTaskFile
   * (so we don't wipe the on-disk description by serializing an empty one).
   */
  async ensureTaskBody(task: Task): Promise<void> {
    if (task.descriptionLoaded) return
    if (!task.filePath) {
      task.descriptionLoaded = true
      return
    }
    const file = this.app.vault.getAbstractFileByPath(task.filePath)
    if (!(file instanceof TFile)) {
      task.descriptionLoaded = true
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { body } = parseFrontmatter(content)
    task.description = stripAutoGeneratedContent(body)
    task.descriptionLoaded = true
  }

  /** Same as ensureTaskBody but for the project file's description body. */
  async ensureProjectBody(project: Project): Promise<void> {
    if (project.descriptionLoaded) return
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (!(file instanceof TFile)) {
      project.descriptionLoaded = true
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { frontmatter, body } = parseFrontmatter(content)
    // Project description lives in frontmatter when set; the body is a fallback
    // for projects that store description in the body. Match hydrateProjectFromFrontmatter.
    const fmDesc = frontmatter?.description
    project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
    project.descriptionLoaded = true
  }

  // ─── Save ──────────────────────────────────────────────────────────────────

  async saveProject(project: Project): Promise<void> {
    const key = project.filePath
    const prev = this.saveQueues.get(key) ?? Promise.resolve()
    const next = prev.then(() => this.doSaveProject(project))
    this.saveQueues.set(
      key,
      next.catch(() => {})
    )
    return next
  }

  private async doSaveProject(project: Project): Promise<void> {
    // Snapshot the dirty set and drop the live entry up front (before any await),
    // so concurrent markDirty calls land in the next save's set, not this one's.
    const dirty = this.dirtyTasks.get(project.filePath) ?? new Set<string>()
    this.dirtyTasks.delete(project.filePath)

    try {
      project.updatedAt = new Date().toISOString()

      const taskFolder = this.projectTaskFolder(project)
      await this.ensureFolder(taskFolder)

      await this.saveAllTasks(project.tasks, project, null, taskFolder, dirty)

      await this.ensureProjectBody(project)
      const content = serializeProject(project, this.getStatuses())
      const file = this.app.vault.getAbstractFileByPath(project.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(project.filePath)
        await this.app.vault.modify(file, content)
      } else {
        await this.app.vault.create(project.filePath, content)
      }
    } catch (e) {
      // Save failed. Merge the snapshot back so the next save retries.
      this.markDirty(project, dirty)
      if (e instanceof TaskFileNameConflictError) throw e
      console.error(`[PM] Failed to save project "${project.title}":`, e)
      new Notice(`Project Manager: Failed to save "${project.title}". Check console for details.`)
      throw e
    }
  }

  private async saveAllTasks(
    tasks: Task[],
    project: Project,
    parentTask: Task | null,
    folder: string,
    dirty: Set<string>
  ): Promise<void> {
    const errors: Error[] = []
    for (const task of tasks) {
      try {
        const needsWrite = dirty.has(task.id) || !task.filePath
        if (needsWrite) {
          let targetFolder = folder
          if (task.archived) {
            targetFolder = normalizePath(folder + '/Archive')
            await this.ensureFolder(targetFolder)
          }
          await this.saveTaskFile(task, project, parentTask, targetFolder)
        }
        if (task.subtasks.length) {
          await this.saveAllTasks(task.subtasks, project, task, folder, dirty)
        }
      } catch (e) {
        errors.push(e instanceof Error ? e : new Error(String(e)))
      }
    }
    if (errors.length) {
      if (errors.length === 1 && errors[0] instanceof TaskFileNameConflictError) throw errors[0]
      throw new Error(`Failed to save ${errors.length} task(s): ${errors.map((e) => e.message).join('; ')}`)
    }
  }

  private async saveTaskFile(task: Task, project: Project, parentTask: Task | null, folder: string): Promise<void> {
    const previousPath = task.filePath
    const filePath = normalizePath(resolveTaskPath(task, folder, previousPath))
    const oldFilePath = previousPath && previousPath !== filePath ? previousPath : null

    // We're about to rewrite the file. If we never loaded the body, pull it now
    // so the on-disk description survives the serialize.
    await this.ensureTaskBody(task)

    try {
      // Write new file first, then delete old — prevents data loss if interrupted
      const content = serializeTask(task, project, parentTask, this.getStatuses())
      const existing = this.app.vault.getAbstractFileByPath(filePath)
      if (existing instanceof TFile) {
        if (existing.path !== previousPath) {
          throw new TaskFileNameConflictError(filePath)
        }
        this.markSelfWrite(filePath)
        await this.app.vault.modify(existing, content)
      } else {
        await this.app.vault.create(filePath, content)
      }
      task.filePath = filePath

      if (oldFilePath) {
        const oldFile = this.app.vault.getAbstractFileByPath(oldFilePath)
        if (oldFile instanceof TFile) {
          this.markSelfWrite(oldFilePath)
          await this.app.fileManager.trashFile(oldFile)
        }
      }
    } catch (e) {
      if (!(e instanceof TaskFileNameConflictError)) {
        console.error(`[PM] Failed to save task "${task.title}" (${task.id}):`, e)
      }
      throw e
    }
  }

  /**
   * Pre-flight check: would saving this task (at its current title) collide
   * with another file already in the vault? Returns a typed error callers can
   * surface inline, or null if the save would proceed cleanly.
   */
  findTaskFileConflict(project: Project, task: Task): TaskFileNameConflictError | null {
    const baseFolder = this.projectTaskFolder(project)
    const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
    const desired = normalizePath(resolveTaskPath(task, folder, task.filePath))
    if (desired === task.filePath) return null
    const existing = this.app.vault.getAbstractFileByPath(desired)
    return existing instanceof TFile ? new TaskFileNameConflictError(desired) : null
  }

  // ─── CRUD shortcuts ────────────────────────────────────────────────────────

  async createProject(title: string, folder: string): Promise<Project> {
    const safeName = title.replace(/[\\/:*?"<>|]/g, '-')
    const filePath = normalizePath(`${folder}/${safeName}.md`)
    const project = makeProject(title, filePath)
    await this.ensureFolder(this.projectTaskFolder(project))
    await this.saveProject(project)
    return project
  }

  async addTask(project: Project, parentId: string | null = null): Promise<Task> {
    const task = makeTask()
    addTaskToTree(project.tasks, task, parentId)
    indexAddSubtree(project, task, parentId)
    this.markDirty(project, [task.id])
    if (parentId) this.markDirty(project, [parentId])
    await this.saveProject(project)
    return task
  }

  async insertTask(project: Project, task: Task, parentId: string | null = null): Promise<void> {
    addTaskToTree(project.tasks, task, parentId)
    indexAddSubtree(project, task, parentId)
    this.markDirty(project, [task.id])
    if (parentId) this.markDirty(project, [parentId])
    await this.saveProject(project)
  }

  async duplicateTask(project: Project, sourceId: string, includeSubtasks: boolean): Promise<Task | null> {
    const source = findTaskById(project, sourceId)
    if (!source) return null
    const copy = cloneTaskSubtree(source, includeSubtasks)
    copy.title = `${source.title} (copy)`
    const parentId = findParentId(project, sourceId)
    addTaskToTree(project.tasks, copy, parentId)
    moveTaskInTree(project.tasks, copy.id, sourceId, 'after')
    indexAddSubtree(project, copy, parentId)
    // Copy and every cloned descendant are new files.
    this.markSubtreeDirty(project, copy.id)
    if (parentId) this.markDirty(project, [parentId])
    await this.saveProject(project)
    return copy
  }

  async moveTask(project: Project, taskId: string, newParentId: string | null): Promise<void> {
    const task = findTaskById(project, taskId)
    if (!task) return
    const oldParentId = findParentId(project, taskId)
    deleteTaskFromTree(project.tasks, taskId)
    addTaskToTree(project.tasks, task, newParentId)
    indexSetParent(project, taskId, newParentId)
    // Moved task's parentId and body link both change.
    this.markDirty(project, [taskId])
    if (oldParentId) this.markDirty(project, [oldParentId])
    if (newParentId) this.markDirty(project, [newParentId])
    await this.saveProject(project)
  }

  async moveTasks(project: Project, taskIds: string[], newParentId: string | null): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const oldParentId = findParentId(project, id)
      deleteTaskFromTree(project.tasks, id)
      addTaskToTree(project.tasks, task, newParentId)
      indexSetParent(project, id, newParentId)
      this.markDirty(project, [id])
      if (oldParentId) this.markDirty(project, [oldParentId])
    }
    if (newParentId) this.markDirty(project, [newParentId])
    await this.saveProject(project)
  }

  async updateTask(project: Project, taskId: string, patch: Partial<Task>): Promise<void> {
    const task = findTaskById(project, taskId)
    const oldTitle = task?.title
    updateTaskInTree(project.tasks, taskId, patch)
    this.markDirty(project, [taskId])
    // Title change renames the file, which breaks direct children's Parent link.
    if (task && patch.title !== undefined && patch.title !== oldTitle) {
      for (const sub of task.subtasks) this.markDirty(project, [sub.id])
    }
    await this.saveProject(project)
  }

  async updateTasks(project: Project, taskIds: string[], patch: Partial<Task>): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      const oldTitle = task?.title
      updateTaskInTree(project.tasks, id, patch)
      this.markDirty(project, [id])
      if (task && patch.title !== undefined && patch.title !== oldTitle) {
        for (const sub of task.subtasks) this.markDirty(project, [sub.id])
      }
    }
    await this.saveProject(project)
  }

  async deleteTasks(project: Project, taskIds: string[]): Promise<void> {
    const folder = this.projectTaskFolder(project)
    const dirtyParents = new Set<string>()
    for (const id of taskIds) {
      const parentId = findParentId(project, id)
      if (parentId) dirtyParents.add(parentId)
      const task = findTaskById(project, id)
      if (task) {
        await this.deleteTaskFiles(task, folder)
        indexRemoveSubtree(project, task)
      }
      deleteTaskFromTree(project.tasks, id)
    }
    if (dirtyParents.size) this.markDirty(project, dirtyParents)
    await this.saveProject(project)
  }

  async archiveTask(project: Project, taskId: string): Promise<void> {
    await doArchiveTask(this.app, project, taskId)
  }

  async unarchiveTask(project: Project, taskId: string): Promise<void> {
    await doUnarchiveTask(this.app, project, taskId)
  }

  async deleteTask(project: Project, taskId: string): Promise<void> {
    const parentId = findParentId(project, taskId)
    const task = findTaskById(project, taskId)
    if (task) {
      await this.deleteTaskFiles(task, this.projectTaskFolder(project))
      indexRemoveSubtree(project, task)
    }
    deleteTaskFromTree(project.tasks, taskId)
    if (parentId) this.markDirty(project, [parentId])
    await this.saveProject(project)
  }

  private async deleteTaskFiles(task: Task, folder: string): Promise<void> {
    for (const sub of task.subtasks) {
      await this.deleteTaskFiles(sub, folder)
    }
    if (task.filePath) {
      const file = this.app.vault.getAbstractFileByPath(task.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(task.filePath)
        await this.app.fileManager.trashFile(file)
      }
    }
  }

  async deleteProject(project: Project): Promise<void> {
    const taskFolder = this.projectTaskFolder(project)
    const folder = this.app.vault.getAbstractFileByPath(taskFolder)
    if (folder instanceof TFolder) {
      await this.deleteFolderRecursive(folder)
    }
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (file instanceof TFile) {
      this.markSelfWrite(project.filePath)
      await this.app.fileManager.trashFile(file)
    }
    this.clearDirty(project)
    this.saveQueues.delete(project.filePath)
  }

  private async deleteFolderRecursive(folder: TFolder): Promise<void> {
    for (const child of [...folder.children]) {
      if (child instanceof TFile) {
        this.markSelfWrite(child.path)
        await this.app.fileManager.trashFile(child)
      } else if (child instanceof TFolder) {
        await this.deleteFolderRecursive(child)
      }
    }
    await this.app.fileManager.trashFile(folder)
  }

  // ─── Scheduling ──────────────────────────────────────────────────────────

  /**
   * Run dependency-based scheduling on the project.
   * Applies computed date patches and saves.
   * Returns the number of tasks that were adjusted.
   */
  async scheduleAfterChange(project: Project, changedTaskId?: string, statuses: StatusConfig[] = []): Promise<number> {
    const { patches } = computeSchedule(project.tasks, changedTaskId, statuses)
    if (patches.length === 0) return 0

    for (const p of patches) {
      updateTaskInTree(project.tasks, p.taskId, { start: p.start, due: p.due })
      this.markDirty(project, [p.taskId])
    }
    await this.saveProject(project)
    return patches.length
  }
}
