import { parseYaml } from 'obsidian';
import type { Project, Task, SavedView, CustomFieldDef } from '../types';
import { makeTask } from '../types';
import { sanitizeFileName } from '../utils';
import { COLOR_ACCENT } from '../constants';

const FRONTMATTER_KEY = 'pm-project';
const TASK_FRONTMATTER_KEY = 'pm-task';

export { FRONTMATTER_KEY, TASK_FRONTMATTER_KEY };

// ─── Parse ──────────────────────────────────────────────────────────────────

export function parseFrontmatter(content: string): {
  frontmatter: Record<string, unknown> | null;
  body: string;
} {
  if (!content.startsWith('---')) return { frontmatter: null, body: content };
  const end = content.indexOf('\n---', 4);
  if (end === -1) return { frontmatter: null, body: content };
  const raw = content.slice(4, end);
  const body = content.slice(end + 4).trim();
  try {
    return { frontmatter: parseYaml(raw) as Record<string, unknown>, body };
  } catch {
    return { frontmatter: null, body: content };
  }
}

/** Strip auto-generated wiki-link lines from task body so they don't get duplicated on save */
export function stripAutoGeneratedContent(body: string): string {
  let result = body;
  result = result.replace(/^Project: \[\[.*\]\]$/gm, '');
  result = result.replace(/^Parent: \[\[.*\]\]$/gm, '');
  result = result.replace(/\n## Subtasks[\s\S]*$/, '');
  return result.trim();
}

// ─── Hydrate ────────────────────────────────────────────────────────────────

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return [];
  return raw.filter(r => r && typeof r === 'object').map(r => {
    const v = r as Record<string, unknown>;
    const filter = (v.filter ?? {}) as Record<string, unknown>;
    return {
      id: (v.id as string) ?? '',
      name: (v.name as string) ?? 'Untitled',
      filter: {
        text: (filter.text as string) ?? '',
        statuses: Array.isArray(filter.statuses) ? filter.statuses : [],
        priorities: Array.isArray(filter.priorities) ? filter.priorities : [],
        assignees: Array.isArray(filter.assignees) ? filter.assignees : [],
        tags: Array.isArray(filter.tags) ? filter.tags : [],
        dueDateFilter: (filter.dueDateFilter as string as SavedView['filter']['dueDateFilter']) ?? 'any',
        showArchived: (filter.showArchived as boolean) ?? false,
      },
      sortKey: (v.sortKey as string) ?? 'status',
      sortDir: (v.sortDir as 'asc' | 'desc') ?? 'asc',
    };
  });
}

/** Map raw frontmatter fields to a Task, with optional overrides */
function mapRawToTask(r: Record<string, unknown>, overrides?: Partial<Task>): Task {
  return makeTask({
    id: r.id as string,
    title: (r.title as string) ?? 'Untitled',
    description: (r.description as string) ?? '',
    type: (r.type as string) === 'milestone' ? 'milestone'
      : (r.type as string) === 'subtask' ? 'subtask'
      : 'task',
    status: (r.status as Task['status']) ?? 'todo',
    priority: (r.priority as Task['priority']) ?? 'medium',
    start: (r.start as string) ?? '',
    due: (r.due as string) ?? '',
    progress: typeof r.progress === 'number' ? r.progress : 0,
    assignees: Array.isArray(r.assignees) ? r.assignees : [],
    tags: Array.isArray(r.tags) ? r.tags : [],
    subtasks: [],
    dependencies: Array.isArray(r.dependencies) ? r.dependencies : [],
    recurrence: r.recurrence && typeof r.recurrence === 'object'
      ? r.recurrence as Task['recurrence']
      : undefined,
    timeEstimate: typeof r.timeEstimate === 'number' ? r.timeEstimate : undefined,
    timeLogs: Array.isArray(r.timeLogs)
      ? (r.timeLogs as { date: string; hours: number; note: string }[])
      : undefined,
    customFields: typeof r.customFields === 'object' && r.customFields !== null
      ? r.customFields as Record<string, unknown>
      : {},
    collapsed: r.collapsed === true,
    createdAt: (r.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (r.updatedAt as string) ?? new Date().toISOString(),
    ...overrides,
  });
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return [];
  return raw.map(r => {
    const rec = r as Record<string, unknown>;
    return mapRawToTask(rec, {
      subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : [],
    });
  });
}

/** Hydrate a task from its frontmatter + body (individual .md file) */
export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
): { task: Task; subtaskIds: string[] } {
  const task = mapRawToTask(frontmatter, {
    description: stripAutoGeneratedContent(body),
    filePath,
  });
  const subtaskIds = Array.isArray(frontmatter.subtaskIds) ? frontmatter.subtaskIds as string[] : [];
  return { task, subtaskIds };
}

/** Build a Project object from frontmatter + body (without tasks) */
export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string,
): Project {
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: (frontmatter.description as string) ?? body.trim(),
    color: (frontmatter.color as string) ?? COLOR_ACCENT,
    icon: (frontmatter.icon as string) ?? '\u{1F4CB}',
    tasks: [],
    customFields: (frontmatter.customFields as CustomFieldDef[]) ?? [],
    teamMembers: (frontmatter.teamMembers as string[]) ?? [],
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? []),
  };
}

// ─── Serialize ──────────────────────────────────────────────────────────────

/** Minimal YAML serializer (handles strings, numbers, booleans, arrays, objects) */
export function appendYaml(lines: string[], obj: Record<string, unknown>, indent: number): void {
  const pad = '  '.repeat(indent);
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) {
      lines.push(`${pad}${key}:`);
    } else if (typeof val === 'boolean') {
      lines.push(`${pad}${key}: ${val}`);
    } else if (typeof val === 'number') {
      lines.push(`${pad}${key}: ${val}`);
    } else if (typeof val === 'string') {
      const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
      lines.push(`${pad}${key}: "${escaped}"`);
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        lines.push(`${pad}${key}: []`);
      } else if (typeof val[0] === 'object') {
        lines.push(`${pad}${key}:`);
        for (const item of val) {
          const entries = Object.entries(item as Record<string, unknown>);
          if (entries.length === 0) continue;
          const [firstKey, firstVal] = entries[0];
          lines.push(`${pad}  - ${firstKey}: ${JSON.stringify(firstVal)}`);
          for (const [k, v] of entries.slice(1)) {
            lines.push(`${pad}    ${k}: ${JSON.stringify(v)}`);
          }
        }
      } else {
        const items = val.map(v => JSON.stringify(v)).join(', ');
        lines.push(`${pad}${key}: [${items}]`);
      }
    } else if (typeof val === 'object') {
      const keys = Object.keys(val as object);
      if (keys.length === 0) {
        lines.push(`${pad}${key}: {}`);
      } else {
        lines.push(`${pad}${key}:`);
        appendYaml(lines, val as Record<string, unknown>, indent + 1);
      }
    }
  }
}

export function serializeProject(project: Project): string {
  const taskIds = project.tasks.map(t => t.id);

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt,
  };

  const yamlLines: string[] = ['---'];
  appendYaml(yamlLines, fm, 0);
  yamlLines.push('---');
  yamlLines.push('');
  yamlLines.push(`# ${project.icon} ${project.title}`);
  yamlLines.push('');
  if (project.description) {
    yamlLines.push(project.description);
    yamlLines.push('');
  }
  if (project.tasks.length) {
    yamlLines.push('## Tasks');
    for (const t of project.tasks) {
      if (t.filePath) {
        const basename = t.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
        const check = t.status === 'done' ? 'x' : t.status === 'cancelled' ? '-' : ' ';
        yamlLines.push(`- [${check}] [[${basename}|${t.title}]]`);
      }
    }
    yamlLines.push('');
  }

  return yamlLines.join('\n');
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
): string {
  const subtaskIds = task.subtasks.map(s => s.id);
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: project.id,
    parentId: parentTask?.id ?? null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    subtaskIds,
    dependencies: task.dependencies,
    collapsed: task.collapsed,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt,
  };
  if (task.recurrence) fm.recurrence = task.recurrence;
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate;
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs;
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields;

  const yamlLines: string[] = ['---'];
  appendYaml(yamlLines, fm, 0);
  yamlLines.push('---');
  yamlLines.push('');
  const cleanDesc = stripAutoGeneratedContent(task.description);
  if (cleanDesc) {
    yamlLines.push(cleanDesc);
    yamlLines.push('');
  }

  if (parentTask?.filePath) {
    const parentBasename = parentTask.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
    yamlLines.push(`Parent: [[${parentBasename}|${parentTask.title}]]`);
  } else {
    const projectBasename = project.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
    yamlLines.push(`Project: [[${projectBasename}|${project.title}]]`);
  }

  if (task.subtasks.length) {
    yamlLines.push('');
    yamlLines.push('## Subtasks');
    for (const sub of task.subtasks) {
      const subSlug = sanitizeFileName(sub.title).toLowerCase().replace(/\s+/g, '-').slice(0, 40);
      const subBasename = `${subSlug}-${sub.id.slice(0, 8)}`;
      const check = sub.status === 'done' ? 'x' : sub.status === 'cancelled' ? '-' : ' ';
      yamlLines.push(`- [${check}] [[${subBasename}|${sub.title}]]`);
    }
  }

  return yamlLines.join('\n');
}

/** Build the file path for a task .md file */
export function taskFilePath(taskTitle: string, taskId: string, folder: string): string {
  const slug = sanitizeFileName(taskTitle).toLowerCase().replace(/\s+/g, '-').slice(0, 40);
  return `${folder}/${slug}-${taskId.slice(0, 8)}.md`;
}

/** Check if a project file uses the old embedded-tasks format */
export function isOldFormat(frontmatter: Record<string, unknown>): boolean {
  return Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0
    && !Array.isArray(frontmatter.taskIds);
}
