import type { Project, Task } from '../types';
import { sanitizeFileName } from '../utils';
import { appendYaml, stripAutoGeneratedContent, FRONTMATTER_KEY, TASK_FRONTMATTER_KEY } from './YamlParser';

// ─── Serialize ──────────────────────────────────────────────────────────────

export function serializeProject(project: Project): string {
  const taskIds = project.tasks.map(t => t.id);

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt,
  };

  const yamlLines: string[] = ['---'];
  appendYaml(yamlLines, fm, 0);
  yamlLines.push('---');
  yamlLines.push('');
  yamlLines.push(`# ${project.icon} ${project.title}`);
  yamlLines.push('');
  if (project.description) {
    yamlLines.push(project.description);
    yamlLines.push('');
  }
  if (project.tasks.length) {
    yamlLines.push('## Tasks');
    for (const t of project.tasks) {
      if (t.filePath) {
        const basename = t.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
        const check = t.status === 'done' ? 'x' : t.status === 'cancelled' ? '-' : ' ';
        yamlLines.push(`- [${check}] [[${basename}|${t.title}]]`);
      }
    }
    yamlLines.push('');
  }

  return yamlLines.join('\n');
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
): string {
  const subtaskIds = task.subtasks.map(s => s.id);
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: project.id,
    parentId: parentTask?.id ?? null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    subtaskIds,
    dependencies: task.dependencies,
    collapsed: task.collapsed,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt,
  };
  if (task.recurrence) fm.recurrence = task.recurrence;
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate;
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs;
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields;

  const yamlLines: string[] = ['---'];
  appendYaml(yamlLines, fm, 0);
  yamlLines.push('---');
  yamlLines.push('');
  const cleanDesc = stripAutoGeneratedContent(task.description);
  if (cleanDesc) {
    yamlLines.push(cleanDesc);
    yamlLines.push('');
  }

  if (parentTask?.filePath) {
    const parentBasename = parentTask.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
    yamlLines.push(`Parent: [[${parentBasename}|${parentTask.title}]]`);
  } else {
    const projectBasename = project.filePath.replace(/^.*\//, '').replace(/\.md$/, '');
    yamlLines.push(`Project: [[${projectBasename}|${project.title}]]`);
  }

  if (task.subtasks.length) {
    yamlLines.push('');
    yamlLines.push('## Subtasks');
    for (const sub of task.subtasks) {
      const subSlug = sanitizeFileName(sub.title).toLowerCase().replace(/\s+/g, '-').slice(0, 40);
      const subBasename = `${subSlug}-${sub.id.slice(0, 8)}`;
      const check = sub.status === 'done' ? 'x' : sub.status === 'cancelled' ? '-' : ' ';
      yamlLines.push(`- [${check}] [[${subBasename}|${sub.title}]]`);
    }
  }

  return yamlLines.join('\n');
}

/** Build the file path for a task .md file */
export function taskFilePath(taskTitle: string, taskId: string, folder: string): string {
  const slug = sanitizeFileName(taskTitle).toLowerCase().replace(/\s+/g, '-').slice(0, 40);
  return `${folder}/${slug}-${taskId.slice(0, 8)}.md`;
}
